/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csproject;

/**
 *
 * @author ddabd
 */
public class AffineCipher extends javax.swing.JFrame {

    /**
     * Creates new form AffineCipher
     */
    
    public AffineCipher() {
        initComponents();
        crypt.setVisible(false);
        this.setResizable(false);
        output.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AValue = new javax.swing.JTextField();
        PlainText = new javax.swing.JTextField();
        BValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crypt = new javax.swing.JPanel();
        labeling = new javax.swing.JLabel();
        output = new javax.swing.JTextField();
        enbtn = new javax.swing.JButton();
        debtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csproject/Screenshot 2025-05-01 200047.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setText("- Affine Cipher Generator");

        AValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AValueActionPerformed(evt);
            }
        });

        PlainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlainTextActionPerformed(evt);
            }
        });

        BValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValueActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel2.setText("Enter Plain Text (Capital Letters, Numbers, Space):");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel4.setText("Value of b:");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel5.setText("Value of a:");

        crypt.setBackground(new java.awt.Color(204, 204, 204));

        labeling.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N

        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cryptLayout = new javax.swing.GroupLayout(crypt);
        crypt.setLayout(cryptLayout);
        cryptLayout.setHorizontalGroup(
            cryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cryptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(output)
                .addContainerGap())
            .addGroup(cryptLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(labeling)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cryptLayout.setVerticalGroup(
            cryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cryptLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labeling)
                .addGap(18, 18, 18)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        enbtn.setBackground(new java.awt.Color(0, 0, 0));
        enbtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        enbtn.setForeground(new java.awt.Color(255, 255, 255));
        enbtn.setText("Encrypt");
        enbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enbtnActionPerformed(evt);
            }
        });

        debtn.setBackground(new java.awt.Color(0, 0, 0));
        debtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        debtn.setForeground(new java.awt.Color(255, 255, 255));
        debtn.setText("Decrypt");
        debtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(PlainText)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AValue, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(BValue, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(crypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(enbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(debtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enbtn)
                    .addComponent(debtn))
                .addGap(29, 29, 29)
                .addComponent(crypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AValueActionPerformed

    private void BValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BValueActionPerformed

    private void PlainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlainTextActionPerformed
    
    private void enbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enbtnActionPerformed
        // TODO add your handling code here:
        crypt.setVisible(true);
         int m = 37;
         
         String text = PlainText.getText() ;
         String av = AValue.getText() ;
         String bv = BValue.getText() ;
         
         int a = Integer.parseInt(av) ;
         int b = Integer.parseInt(bv) ;
         
          // Encrypt
        String cipher = "";
        for (int i = 0; i < text.length(); i++) {
            char ch = text.charAt(i);
            int x = getNumber(ch);
            int enc = (a * x + b) % m;
            cipher = cipher + getChar(enc);
        }
        
        labeling.setText("Encrypted Text:");
        output.setText(cipher);
       
        
        
    }//GEN-LAST:event_enbtnActionPerformed

    private void debtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtnActionPerformed
        // TODO add your handling code here:
        crypt.setVisible(true);
         int m = 37;
         
         String text = PlainText.getText() ;
         String av = AValue.getText() ;
         String bv = BValue.getText() ;
         
         int a = Integer.parseInt(av) ;
         int b = Integer.parseInt(bv) ;
         
         // Find modular inverse of a
        int a_inv = -1;
        for (int i = 0; i < m; i++) {
            if ((a * i) % m == 1) {
                a_inv = i;
                break;
            }
        }
        
        // Decrypt
        String decrypted = "";
        for (int i = 0; i < text.length(); i++) {
            char ch = text.charAt(i);
            int y = getNumber(ch);
            int dec = (a_inv * (y - b + m)) % m;
            decrypted = decrypted + getChar(dec);
            
        }
        
        labeling.setText("Decrypted Text:");
        output.setText(decrypted);
    }//GEN-LAST:event_debtnActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    // Get number for a character
    public static int getNumber(char ch) {
        if (ch >= 'A' && ch <= 'Z') {
            return ch - 'A'; // A=0, B=1, ..., Z=25
        } else if (ch >= '0' && ch <= '9') {
            return 26 + (ch - '0'); // 0=26, 1=27, ..., 9=35
        } else if (ch == ' ') {
            return 36; // Space = 36
        } else {
            return -1; // Not allowed
        }
    }
    
    // Get character for a number
    public static char getChar(int num) {
        if (num >= 0 && num <= 25) {
            return (char) ('A' + num);
        } else if (num >= 26 && num <= 35) {
            return (char) ('0' + (num - 26));
        } else if (num == 36) {
            return ' ';
        } else {
            return '?'; // Not allowed
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffineCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffineCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffineCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffineCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffineCipher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AValue;
    private javax.swing.JTextField BValue;
    private javax.swing.JTextField PlainText;
    private javax.swing.JPanel crypt;
    private javax.swing.JButton debtn;
    private javax.swing.JButton enbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeling;
    private javax.swing.JTextField output;
    // End of variables declaration//GEN-END:variables

}
